### ISSUE TITLE
Playlist doesn't play next musics

### ISSUE THREAD

**Issue by MrKoddy** [Fraeio/Music-Module#7]
**Steps to reproduce the behavior:**
1. Go to a playlist
2. Play a music in this playlist, wait until it ends and load the next music
3. It plays another music in the main dashboard, not in the playlist dashboard

**Expected behavior**
Playlist should play musics which are only in the playlist, not elsewhere

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 100

**Comment by LovBlueFox** [comment]
I fixed the issue; thanks for reporting!
